[env:esp32dev]
platform = platformio/espressif32@^6.1.0
board = esp32dev
framework = arduino

monitor_speed = 115200
board_build.filesystem = littlefs
board_build.partitions = partitions.csv

lib_deps =
    milesburton/DallasTemperature
    paulstoffregen/OneWire
    adafruit/RTClib
    bblanchon/ArduinoJson@^7
